// @generated by protoc-gen-es v2.2.3 with parameter "target=ts,json_types=true"
// @generated from file web-ui/service_playtest.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_web_ui_common_base } from "./common_base_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file web-ui/service_playtest.proto.
 */
export const file_web_ui_service_playtest: GenFile = /*@__PURE__*/
  fileDesc("Ch13ZWItdWkvc2VydmljZV9wbGF5dGVzdC5wcm90byIxChxDUGxheXRlc3RfR2V0SW52aXRlc19SZXF1ZXN0EhEKCWludml0ZV9pZBgBIAEoBCJXCh1DUGxheXRlc3RfR2V0SW52aXRlc19SZXNwb25zZRI2CgdpbnZpdGVzGAEgAygLMiUuQ1BsYXl0ZXN0X0dldEludml0ZXNfUmVzcG9uc2VfSW52aXRlIqMBCiRDUGxheXRlc3RfR2V0SW52aXRlc19SZXNwb25zZV9JbnZpdGUSEQoJaW52aXRlX2lkGAEgASgEEg0KBWFwcGlkGAIgASgNEhcKD3N0ZWFtaWRfaW52aXRlchgDIAEoBhIYCgZzdGF0dXMYBCABKAVCCIK1GARlbnVtEhQKDHRpbWVfY3JlYXRlZBgFIAEoDRIQCghhcHBfbmFtZRgGIAEoCSIhCh9DUGxheXRlc3RfR2V0VXNlclN0YXR1c19SZXF1ZXN0ImAKIENQbGF5dGVzdF9HZXRVc2VyU3RhdHVzX1Jlc3BvbnNlEjwKB3Jlc3VsdHMYASADKAsyKy5DUGxheXRlc3RfR2V0VXNlclN0YXR1c19SZXNwb25zZV9BcHBTdGF0dXMicAoqQ1BsYXl0ZXN0X0dldFVzZXJTdGF0dXNfUmVzcG9uc2VfQXBwU3RhdHVzEg0KBWFwcGlkGAEgASgNEhgKBnN0YXR1cxgCIAEoBUIIgrUYBGVudW0SGQoRaW52aXRlc19yZW1haW5pbmcYAyABKAUiQQofQ1BsYXl0ZXN0X1JlcXVlc3RJbnZpdGVfUmVxdWVzdBINCgVhcHBpZBgBIAEoDRIPCgdzdGVhbWlkGAIgASgGIlcKIENQbGF5dGVzdF9SZXF1ZXN0SW52aXRlX1Jlc3BvbnNlEhkKEWludml0ZXNfcmVtYWluaW5nGAEgASgFEhgKBnN0YXR1cxgCIAEoBUIIgrUYBGVudW0iTwofQ1BsYXl0ZXN0X1VwZGF0ZUludml0ZXNfUmVxdWVzdBISCgppbnZpdGVfaWRzGAEgAygEEhgKBnN0YXR1cxgCIAEoBUIIgrUYBGVudW0iOwogQ1BsYXl0ZXN0X1VwZGF0ZUludml0ZXNfUmVzcG9uc2USFwoPaW52aXRlc191cGRhdGVkGAEgASgNMtkCCghQbGF5dGVzdBJLCgpHZXRJbnZpdGVzEh0uQ1BsYXl0ZXN0X0dldEludml0ZXNfUmVxdWVzdBoeLkNQbGF5dGVzdF9HZXRJbnZpdGVzX1Jlc3BvbnNlElQKDUdldFVzZXJTdGF0dXMSIC5DUGxheXRlc3RfR2V0VXNlclN0YXR1c19SZXF1ZXN0GiEuQ1BsYXl0ZXN0X0dldFVzZXJTdGF0dXNfUmVzcG9uc2USVAoNUmVxdWVzdEludml0ZRIgLkNQbGF5dGVzdF9SZXF1ZXN0SW52aXRlX1JlcXVlc3QaIS5DUGxheXRlc3RfUmVxdWVzdEludml0ZV9SZXNwb25zZRJUCg1VcGRhdGVJbnZpdGVzEiAuQ1BsYXl0ZXN0X1VwZGF0ZUludml0ZXNfUmVxdWVzdBohLkNQbGF5dGVzdF9VcGRhdGVJbnZpdGVzX1Jlc3BvbnNl", [file_web_ui_common_base]);

/**
 * @generated from message CPlaytest_GetInvites_Request
 */
export type CPlaytest_GetInvites_Request = Message<"CPlaytest_GetInvites_Request"> & {
  /**
   * @generated from field: optional uint64 invite_id = 1;
   */
  inviteId: bigint;
};

/**
 * @generated from message CPlaytest_GetInvites_Request
 */
export type CPlaytest_GetInvites_RequestJson = {
  /**
   * @generated from field: optional uint64 invite_id = 1;
   */
  inviteId?: string;
};

/**
 * Describes the message CPlaytest_GetInvites_Request.
 * Use `create(CPlaytest_GetInvites_RequestSchema)` to create a new message.
 */
export const CPlaytest_GetInvites_RequestSchema: GenMessage<CPlaytest_GetInvites_Request, CPlaytest_GetInvites_RequestJson> = /*@__PURE__*/
  messageDesc(file_web_ui_service_playtest, 0);

/**
 * @generated from message CPlaytest_GetInvites_Response
 */
export type CPlaytest_GetInvites_Response = Message<"CPlaytest_GetInvites_Response"> & {
  /**
   * @generated from field: repeated CPlaytest_GetInvites_Response_Invite invites = 1;
   */
  invites: CPlaytest_GetInvites_Response_Invite[];
};

/**
 * @generated from message CPlaytest_GetInvites_Response
 */
export type CPlaytest_GetInvites_ResponseJson = {
  /**
   * @generated from field: repeated CPlaytest_GetInvites_Response_Invite invites = 1;
   */
  invites?: CPlaytest_GetInvites_Response_InviteJson[];
};

/**
 * Describes the message CPlaytest_GetInvites_Response.
 * Use `create(CPlaytest_GetInvites_ResponseSchema)` to create a new message.
 */
export const CPlaytest_GetInvites_ResponseSchema: GenMessage<CPlaytest_GetInvites_Response, CPlaytest_GetInvites_ResponseJson> = /*@__PURE__*/
  messageDesc(file_web_ui_service_playtest, 1);

/**
 * @generated from message CPlaytest_GetInvites_Response_Invite
 */
export type CPlaytest_GetInvites_Response_Invite = Message<"CPlaytest_GetInvites_Response_Invite"> & {
  /**
   * @generated from field: optional uint64 invite_id = 1;
   */
  inviteId: bigint;

  /**
   * @generated from field: optional uint32 appid = 2;
   */
  appid: number;

  /**
   * @generated from field: optional fixed64 steamid_inviter = 3;
   */
  steamidInviter: bigint;

  /**
   * @generated from field: optional int32 status = 4;
   */
  status: number;

  /**
   * @generated from field: optional uint32 time_created = 5;
   */
  timeCreated: number;

  /**
   * @generated from field: optional string app_name = 6;
   */
  appName: string;
};

/**
 * @generated from message CPlaytest_GetInvites_Response_Invite
 */
export type CPlaytest_GetInvites_Response_InviteJson = {
  /**
   * @generated from field: optional uint64 invite_id = 1;
   */
  inviteId?: string;

  /**
   * @generated from field: optional uint32 appid = 2;
   */
  appid?: number;

  /**
   * @generated from field: optional fixed64 steamid_inviter = 3;
   */
  steamidInviter?: string;

  /**
   * @generated from field: optional int32 status = 4;
   */
  status?: number;

  /**
   * @generated from field: optional uint32 time_created = 5;
   */
  timeCreated?: number;

  /**
   * @generated from field: optional string app_name = 6;
   */
  appName?: string;
};

/**
 * Describes the message CPlaytest_GetInvites_Response_Invite.
 * Use `create(CPlaytest_GetInvites_Response_InviteSchema)` to create a new message.
 */
export const CPlaytest_GetInvites_Response_InviteSchema: GenMessage<CPlaytest_GetInvites_Response_Invite, CPlaytest_GetInvites_Response_InviteJson> = /*@__PURE__*/
  messageDesc(file_web_ui_service_playtest, 2);

/**
 * @generated from message CPlaytest_GetUserStatus_Request
 */
export type CPlaytest_GetUserStatus_Request = Message<"CPlaytest_GetUserStatus_Request"> & {
};

/**
 * @generated from message CPlaytest_GetUserStatus_Request
 */
export type CPlaytest_GetUserStatus_RequestJson = {
};

/**
 * Describes the message CPlaytest_GetUserStatus_Request.
 * Use `create(CPlaytest_GetUserStatus_RequestSchema)` to create a new message.
 */
export const CPlaytest_GetUserStatus_RequestSchema: GenMessage<CPlaytest_GetUserStatus_Request, CPlaytest_GetUserStatus_RequestJson> = /*@__PURE__*/
  messageDesc(file_web_ui_service_playtest, 3);

/**
 * @generated from message CPlaytest_GetUserStatus_Response
 */
export type CPlaytest_GetUserStatus_Response = Message<"CPlaytest_GetUserStatus_Response"> & {
  /**
   * @generated from field: repeated CPlaytest_GetUserStatus_Response_AppStatus results = 1;
   */
  results: CPlaytest_GetUserStatus_Response_AppStatus[];
};

/**
 * @generated from message CPlaytest_GetUserStatus_Response
 */
export type CPlaytest_GetUserStatus_ResponseJson = {
  /**
   * @generated from field: repeated CPlaytest_GetUserStatus_Response_AppStatus results = 1;
   */
  results?: CPlaytest_GetUserStatus_Response_AppStatusJson[];
};

/**
 * Describes the message CPlaytest_GetUserStatus_Response.
 * Use `create(CPlaytest_GetUserStatus_ResponseSchema)` to create a new message.
 */
export const CPlaytest_GetUserStatus_ResponseSchema: GenMessage<CPlaytest_GetUserStatus_Response, CPlaytest_GetUserStatus_ResponseJson> = /*@__PURE__*/
  messageDesc(file_web_ui_service_playtest, 4);

/**
 * @generated from message CPlaytest_GetUserStatus_Response_AppStatus
 */
export type CPlaytest_GetUserStatus_Response_AppStatus = Message<"CPlaytest_GetUserStatus_Response_AppStatus"> & {
  /**
   * @generated from field: optional uint32 appid = 1;
   */
  appid: number;

  /**
   * @generated from field: optional int32 status = 2;
   */
  status: number;

  /**
   * @generated from field: optional int32 invites_remaining = 3;
   */
  invitesRemaining: number;
};

/**
 * @generated from message CPlaytest_GetUserStatus_Response_AppStatus
 */
export type CPlaytest_GetUserStatus_Response_AppStatusJson = {
  /**
   * @generated from field: optional uint32 appid = 1;
   */
  appid?: number;

  /**
   * @generated from field: optional int32 status = 2;
   */
  status?: number;

  /**
   * @generated from field: optional int32 invites_remaining = 3;
   */
  invitesRemaining?: number;
};

/**
 * Describes the message CPlaytest_GetUserStatus_Response_AppStatus.
 * Use `create(CPlaytest_GetUserStatus_Response_AppStatusSchema)` to create a new message.
 */
export const CPlaytest_GetUserStatus_Response_AppStatusSchema: GenMessage<CPlaytest_GetUserStatus_Response_AppStatus, CPlaytest_GetUserStatus_Response_AppStatusJson> = /*@__PURE__*/
  messageDesc(file_web_ui_service_playtest, 5);

/**
 * @generated from message CPlaytest_RequestInvite_Request
 */
export type CPlaytest_RequestInvite_Request = Message<"CPlaytest_RequestInvite_Request"> & {
  /**
   * @generated from field: optional uint32 appid = 1;
   */
  appid: number;

  /**
   * @generated from field: optional fixed64 steamid = 2;
   */
  steamid: bigint;
};

/**
 * @generated from message CPlaytest_RequestInvite_Request
 */
export type CPlaytest_RequestInvite_RequestJson = {
  /**
   * @generated from field: optional uint32 appid = 1;
   */
  appid?: number;

  /**
   * @generated from field: optional fixed64 steamid = 2;
   */
  steamid?: string;
};

/**
 * Describes the message CPlaytest_RequestInvite_Request.
 * Use `create(CPlaytest_RequestInvite_RequestSchema)` to create a new message.
 */
export const CPlaytest_RequestInvite_RequestSchema: GenMessage<CPlaytest_RequestInvite_Request, CPlaytest_RequestInvite_RequestJson> = /*@__PURE__*/
  messageDesc(file_web_ui_service_playtest, 6);

/**
 * @generated from message CPlaytest_RequestInvite_Response
 */
export type CPlaytest_RequestInvite_Response = Message<"CPlaytest_RequestInvite_Response"> & {
  /**
   * @generated from field: optional int32 invites_remaining = 1;
   */
  invitesRemaining: number;

  /**
   * @generated from field: optional int32 status = 2;
   */
  status: number;
};

/**
 * @generated from message CPlaytest_RequestInvite_Response
 */
export type CPlaytest_RequestInvite_ResponseJson = {
  /**
   * @generated from field: optional int32 invites_remaining = 1;
   */
  invitesRemaining?: number;

  /**
   * @generated from field: optional int32 status = 2;
   */
  status?: number;
};

/**
 * Describes the message CPlaytest_RequestInvite_Response.
 * Use `create(CPlaytest_RequestInvite_ResponseSchema)` to create a new message.
 */
export const CPlaytest_RequestInvite_ResponseSchema: GenMessage<CPlaytest_RequestInvite_Response, CPlaytest_RequestInvite_ResponseJson> = /*@__PURE__*/
  messageDesc(file_web_ui_service_playtest, 7);

/**
 * @generated from message CPlaytest_UpdateInvites_Request
 */
export type CPlaytest_UpdateInvites_Request = Message<"CPlaytest_UpdateInvites_Request"> & {
  /**
   * @generated from field: repeated uint64 invite_ids = 1;
   */
  inviteIds: bigint[];

  /**
   * @generated from field: optional int32 status = 2;
   */
  status: number;
};

/**
 * @generated from message CPlaytest_UpdateInvites_Request
 */
export type CPlaytest_UpdateInvites_RequestJson = {
  /**
   * @generated from field: repeated uint64 invite_ids = 1;
   */
  inviteIds?: string[];

  /**
   * @generated from field: optional int32 status = 2;
   */
  status?: number;
};

/**
 * Describes the message CPlaytest_UpdateInvites_Request.
 * Use `create(CPlaytest_UpdateInvites_RequestSchema)` to create a new message.
 */
export const CPlaytest_UpdateInvites_RequestSchema: GenMessage<CPlaytest_UpdateInvites_Request, CPlaytest_UpdateInvites_RequestJson> = /*@__PURE__*/
  messageDesc(file_web_ui_service_playtest, 8);

/**
 * @generated from message CPlaytest_UpdateInvites_Response
 */
export type CPlaytest_UpdateInvites_Response = Message<"CPlaytest_UpdateInvites_Response"> & {
  /**
   * @generated from field: optional uint32 invites_updated = 1;
   */
  invitesUpdated: number;
};

/**
 * @generated from message CPlaytest_UpdateInvites_Response
 */
export type CPlaytest_UpdateInvites_ResponseJson = {
  /**
   * @generated from field: optional uint32 invites_updated = 1;
   */
  invitesUpdated?: number;
};

/**
 * Describes the message CPlaytest_UpdateInvites_Response.
 * Use `create(CPlaytest_UpdateInvites_ResponseSchema)` to create a new message.
 */
export const CPlaytest_UpdateInvites_ResponseSchema: GenMessage<CPlaytest_UpdateInvites_Response, CPlaytest_UpdateInvites_ResponseJson> = /*@__PURE__*/
  messageDesc(file_web_ui_service_playtest, 9);

/**
 * @generated from service Playtest
 */
export const Playtest: GenService<{
  /**
   * @generated from rpc Playtest.GetInvites
   */
  getInvites: {
    methodKind: "unary";
    input: typeof CPlaytest_GetInvites_RequestSchema;
    output: typeof CPlaytest_GetInvites_ResponseSchema;
  },
  /**
   * @generated from rpc Playtest.GetUserStatus
   */
  getUserStatus: {
    methodKind: "unary";
    input: typeof CPlaytest_GetUserStatus_RequestSchema;
    output: typeof CPlaytest_GetUserStatus_ResponseSchema;
  },
  /**
   * @generated from rpc Playtest.RequestInvite
   */
  requestInvite: {
    methodKind: "unary";
    input: typeof CPlaytest_RequestInvite_RequestSchema;
    output: typeof CPlaytest_RequestInvite_ResponseSchema;
  },
  /**
   * @generated from rpc Playtest.UpdateInvites
   */
  updateInvites: {
    methodKind: "unary";
    input: typeof CPlaytest_UpdateInvites_RequestSchema;
    output: typeof CPlaytest_UpdateInvites_ResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_web_ui_service_playtest, 0);

