// @generated by protoc-gen-es v2.2.3 with parameter "target=ts,json_types=true"
// @generated from file web-ui/service_cloudconfigstore.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { NoResponseSchema } from "./common_base_pb";
import { file_web_ui_common_base } from "./common_base_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file web-ui/service_cloudconfigstore.proto.
 */
export const file_web_ui_service_cloudconfigstore: GenFile = /*@__PURE__*/
  fileDesc("CiV3ZWItdWkvc2VydmljZV9jbG91ZGNvbmZpZ3N0b3JlLnByb3RvIl4KJUNDbG91ZENvbmZpZ1N0b3JlX0NoYW5nZV9Ob3RpZmljYXRpb24SNQoIdmVyc2lvbnMYAiADKAsyIy5DQ2xvdWRDb25maWdTdG9yZV9OYW1lc3BhY2VWZXJzaW9uIlsKIkNDbG91ZENvbmZpZ1N0b3JlX0Rvd25sb2FkX1JlcXVlc3QSNQoIdmVyc2lvbnMYASADKAsyIy5DQ2xvdWRDb25maWdTdG9yZV9OYW1lc3BhY2VWZXJzaW9uIlUKI0NDbG91ZENvbmZpZ1N0b3JlX0Rvd25sb2FkX1Jlc3BvbnNlEi4KBGRhdGEYASADKAsyIC5DQ2xvdWRDb25maWdTdG9yZV9OYW1lc3BhY2VEYXRhIm0KF0NDbG91ZENvbmZpZ1N0b3JlX0VudHJ5EgsKA2tleRgBIAEoCRISCgppc19kZWxldGVkGAIgASgIEg0KBXZhbHVlGAMgASgJEhEKCXRpbWVzdGFtcBgEIAEoBxIPCgd2ZXJzaW9uGAUgASgEIoIBCh9DQ2xvdWRDb25maWdTdG9yZV9OYW1lc3BhY2VEYXRhEhIKCmVuYW1lc3BhY2UYASABKA0SDwoHdmVyc2lvbhgCIAEoBBIpCgdlbnRyaWVzGAMgAygLMhguQ0Nsb3VkQ29uZmlnU3RvcmVfRW50cnkSDwoHaG9yaXpvbhgEIAEoBCJJCiJDQ2xvdWRDb25maWdTdG9yZV9OYW1lc3BhY2VWZXJzaW9uEhIKCmVuYW1lc3BhY2UYASABKA0SDwoHdmVyc2lvbhgCIAEoBCJSCiBDQ2xvdWRDb25maWdTdG9yZV9VcGxvYWRfUmVxdWVzdBIuCgRkYXRhGAEgAygLMiAuQ0Nsb3VkQ29uZmlnU3RvcmVfTmFtZXNwYWNlRGF0YSJaCiFDQ2xvdWRDb25maWdTdG9yZV9VcGxvYWRfUmVzcG9uc2USNQoIdmVyc2lvbnMYASADKAsyIy5DQ2xvdWRDb25maWdTdG9yZV9OYW1lc3BhY2VWZXJzaW9uMroBChBDbG91ZENvbmZpZ1N0b3JlElUKCERvd25sb2FkEiMuQ0Nsb3VkQ29uZmlnU3RvcmVfRG93bmxvYWRfUmVxdWVzdBokLkNDbG91ZENvbmZpZ1N0b3JlX0Rvd25sb2FkX1Jlc3BvbnNlEk8KBlVwbG9hZBIhLkNDbG91ZENvbmZpZ1N0b3JlX1VwbG9hZF9SZXF1ZXN0GiIuQ0Nsb3VkQ29uZmlnU3RvcmVfVXBsb2FkX1Jlc3BvbnNlMl0KFkNsb3VkQ29uZmlnU3RvcmVDbGllbnQSQwoMTm90aWZ5Q2hhbmdlEiYuQ0Nsb3VkQ29uZmlnU3RvcmVfQ2hhbmdlX05vdGlmaWNhdGlvbhoLLk5vUmVzcG9uc2U", [file_web_ui_common_base]);

/**
 * @generated from message CCloudConfigStore_Change_Notification
 */
export type CCloudConfigStore_Change_Notification = Message<"CCloudConfigStore_Change_Notification"> & {
  /**
   * @generated from field: repeated CCloudConfigStore_NamespaceVersion versions = 2;
   */
  versions: CCloudConfigStore_NamespaceVersion[];
};

/**
 * @generated from message CCloudConfigStore_Change_Notification
 */
export type CCloudConfigStore_Change_NotificationJson = {
  /**
   * @generated from field: repeated CCloudConfigStore_NamespaceVersion versions = 2;
   */
  versions?: CCloudConfigStore_NamespaceVersionJson[];
};

/**
 * Describes the message CCloudConfigStore_Change_Notification.
 * Use `create(CCloudConfigStore_Change_NotificationSchema)` to create a new message.
 */
export const CCloudConfigStore_Change_NotificationSchema: GenMessage<CCloudConfigStore_Change_Notification, CCloudConfigStore_Change_NotificationJson> = /*@__PURE__*/
  messageDesc(file_web_ui_service_cloudconfigstore, 0);

/**
 * @generated from message CCloudConfigStore_Download_Request
 */
export type CCloudConfigStore_Download_Request = Message<"CCloudConfigStore_Download_Request"> & {
  /**
   * @generated from field: repeated CCloudConfigStore_NamespaceVersion versions = 1;
   */
  versions: CCloudConfigStore_NamespaceVersion[];
};

/**
 * @generated from message CCloudConfigStore_Download_Request
 */
export type CCloudConfigStore_Download_RequestJson = {
  /**
   * @generated from field: repeated CCloudConfigStore_NamespaceVersion versions = 1;
   */
  versions?: CCloudConfigStore_NamespaceVersionJson[];
};

/**
 * Describes the message CCloudConfigStore_Download_Request.
 * Use `create(CCloudConfigStore_Download_RequestSchema)` to create a new message.
 */
export const CCloudConfigStore_Download_RequestSchema: GenMessage<CCloudConfigStore_Download_Request, CCloudConfigStore_Download_RequestJson> = /*@__PURE__*/
  messageDesc(file_web_ui_service_cloudconfigstore, 1);

/**
 * @generated from message CCloudConfigStore_Download_Response
 */
export type CCloudConfigStore_Download_Response = Message<"CCloudConfigStore_Download_Response"> & {
  /**
   * @generated from field: repeated CCloudConfigStore_NamespaceData data = 1;
   */
  data: CCloudConfigStore_NamespaceData[];
};

/**
 * @generated from message CCloudConfigStore_Download_Response
 */
export type CCloudConfigStore_Download_ResponseJson = {
  /**
   * @generated from field: repeated CCloudConfigStore_NamespaceData data = 1;
   */
  data?: CCloudConfigStore_NamespaceDataJson[];
};

/**
 * Describes the message CCloudConfigStore_Download_Response.
 * Use `create(CCloudConfigStore_Download_ResponseSchema)` to create a new message.
 */
export const CCloudConfigStore_Download_ResponseSchema: GenMessage<CCloudConfigStore_Download_Response, CCloudConfigStore_Download_ResponseJson> = /*@__PURE__*/
  messageDesc(file_web_ui_service_cloudconfigstore, 2);

/**
 * @generated from message CCloudConfigStore_Entry
 */
export type CCloudConfigStore_Entry = Message<"CCloudConfigStore_Entry"> & {
  /**
   * @generated from field: optional string key = 1;
   */
  key: string;

  /**
   * @generated from field: optional bool is_deleted = 2;
   */
  isDeleted: boolean;

  /**
   * @generated from field: optional string value = 3;
   */
  value: string;

  /**
   * @generated from field: optional fixed32 timestamp = 4;
   */
  timestamp: number;

  /**
   * @generated from field: optional uint64 version = 5;
   */
  version: bigint;
};

/**
 * @generated from message CCloudConfigStore_Entry
 */
export type CCloudConfigStore_EntryJson = {
  /**
   * @generated from field: optional string key = 1;
   */
  key?: string;

  /**
   * @generated from field: optional bool is_deleted = 2;
   */
  isDeleted?: boolean;

  /**
   * @generated from field: optional string value = 3;
   */
  value?: string;

  /**
   * @generated from field: optional fixed32 timestamp = 4;
   */
  timestamp?: number;

  /**
   * @generated from field: optional uint64 version = 5;
   */
  version?: string;
};

/**
 * Describes the message CCloudConfigStore_Entry.
 * Use `create(CCloudConfigStore_EntrySchema)` to create a new message.
 */
export const CCloudConfigStore_EntrySchema: GenMessage<CCloudConfigStore_Entry, CCloudConfigStore_EntryJson> = /*@__PURE__*/
  messageDesc(file_web_ui_service_cloudconfigstore, 3);

/**
 * @generated from message CCloudConfigStore_NamespaceData
 */
export type CCloudConfigStore_NamespaceData = Message<"CCloudConfigStore_NamespaceData"> & {
  /**
   * @generated from field: optional uint32 enamespace = 1;
   */
  enamespace: number;

  /**
   * @generated from field: optional uint64 version = 2;
   */
  version: bigint;

  /**
   * @generated from field: repeated CCloudConfigStore_Entry entries = 3;
   */
  entries: CCloudConfigStore_Entry[];

  /**
   * @generated from field: optional uint64 horizon = 4;
   */
  horizon: bigint;
};

/**
 * @generated from message CCloudConfigStore_NamespaceData
 */
export type CCloudConfigStore_NamespaceDataJson = {
  /**
   * @generated from field: optional uint32 enamespace = 1;
   */
  enamespace?: number;

  /**
   * @generated from field: optional uint64 version = 2;
   */
  version?: string;

  /**
   * @generated from field: repeated CCloudConfigStore_Entry entries = 3;
   */
  entries?: CCloudConfigStore_EntryJson[];

  /**
   * @generated from field: optional uint64 horizon = 4;
   */
  horizon?: string;
};

/**
 * Describes the message CCloudConfigStore_NamespaceData.
 * Use `create(CCloudConfigStore_NamespaceDataSchema)` to create a new message.
 */
export const CCloudConfigStore_NamespaceDataSchema: GenMessage<CCloudConfigStore_NamespaceData, CCloudConfigStore_NamespaceDataJson> = /*@__PURE__*/
  messageDesc(file_web_ui_service_cloudconfigstore, 4);

/**
 * @generated from message CCloudConfigStore_NamespaceVersion
 */
export type CCloudConfigStore_NamespaceVersion = Message<"CCloudConfigStore_NamespaceVersion"> & {
  /**
   * @generated from field: optional uint32 enamespace = 1;
   */
  enamespace: number;

  /**
   * @generated from field: optional uint64 version = 2;
   */
  version: bigint;
};

/**
 * @generated from message CCloudConfigStore_NamespaceVersion
 */
export type CCloudConfigStore_NamespaceVersionJson = {
  /**
   * @generated from field: optional uint32 enamespace = 1;
   */
  enamespace?: number;

  /**
   * @generated from field: optional uint64 version = 2;
   */
  version?: string;
};

/**
 * Describes the message CCloudConfigStore_NamespaceVersion.
 * Use `create(CCloudConfigStore_NamespaceVersionSchema)` to create a new message.
 */
export const CCloudConfigStore_NamespaceVersionSchema: GenMessage<CCloudConfigStore_NamespaceVersion, CCloudConfigStore_NamespaceVersionJson> = /*@__PURE__*/
  messageDesc(file_web_ui_service_cloudconfigstore, 5);

/**
 * @generated from message CCloudConfigStore_Upload_Request
 */
export type CCloudConfigStore_Upload_Request = Message<"CCloudConfigStore_Upload_Request"> & {
  /**
   * @generated from field: repeated CCloudConfigStore_NamespaceData data = 1;
   */
  data: CCloudConfigStore_NamespaceData[];
};

/**
 * @generated from message CCloudConfigStore_Upload_Request
 */
export type CCloudConfigStore_Upload_RequestJson = {
  /**
   * @generated from field: repeated CCloudConfigStore_NamespaceData data = 1;
   */
  data?: CCloudConfigStore_NamespaceDataJson[];
};

/**
 * Describes the message CCloudConfigStore_Upload_Request.
 * Use `create(CCloudConfigStore_Upload_RequestSchema)` to create a new message.
 */
export const CCloudConfigStore_Upload_RequestSchema: GenMessage<CCloudConfigStore_Upload_Request, CCloudConfigStore_Upload_RequestJson> = /*@__PURE__*/
  messageDesc(file_web_ui_service_cloudconfigstore, 6);

/**
 * @generated from message CCloudConfigStore_Upload_Response
 */
export type CCloudConfigStore_Upload_Response = Message<"CCloudConfigStore_Upload_Response"> & {
  /**
   * @generated from field: repeated CCloudConfigStore_NamespaceVersion versions = 1;
   */
  versions: CCloudConfigStore_NamespaceVersion[];
};

/**
 * @generated from message CCloudConfigStore_Upload_Response
 */
export type CCloudConfigStore_Upload_ResponseJson = {
  /**
   * @generated from field: repeated CCloudConfigStore_NamespaceVersion versions = 1;
   */
  versions?: CCloudConfigStore_NamespaceVersionJson[];
};

/**
 * Describes the message CCloudConfigStore_Upload_Response.
 * Use `create(CCloudConfigStore_Upload_ResponseSchema)` to create a new message.
 */
export const CCloudConfigStore_Upload_ResponseSchema: GenMessage<CCloudConfigStore_Upload_Response, CCloudConfigStore_Upload_ResponseJson> = /*@__PURE__*/
  messageDesc(file_web_ui_service_cloudconfigstore, 7);

/**
 * @generated from service CloudConfigStore
 */
export const CloudConfigStore: GenService<{
  /**
   * @generated from rpc CloudConfigStore.Download
   */
  download: {
    methodKind: "unary";
    input: typeof CCloudConfigStore_Download_RequestSchema;
    output: typeof CCloudConfigStore_Download_ResponseSchema;
  },
  /**
   * @generated from rpc CloudConfigStore.Upload
   */
  upload: {
    methodKind: "unary";
    input: typeof CCloudConfigStore_Upload_RequestSchema;
    output: typeof CCloudConfigStore_Upload_ResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_web_ui_service_cloudconfigstore, 0);

/**
 * @generated from service CloudConfigStoreClient
 */
export const CloudConfigStoreClient: GenService<{
  /**
   * @generated from rpc CloudConfigStoreClient.NotifyChange
   */
  notifyChange: {
    methodKind: "unary";
    input: typeof CCloudConfigStore_Change_NotificationSchema;
    output: typeof NoResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_web_ui_service_cloudconfigstore, 1);

