// @generated by protoc-gen-es v2.2.3 with parameter "target=ts,json_types=true"
// @generated from file web-ui/service_accountprivateapps.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { NoResponseSchema } from "./common_base_pb";
import { file_web_ui_common_base } from "./common_base_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file web-ui/service_accountprivateapps.proto.
 */
export const file_web_ui_service_accountprivateapps: GenFile = /*@__PURE__*/
  fileDesc("Cid3ZWItdWkvc2VydmljZV9hY2NvdW50cHJpdmF0ZWFwcHMucHJvdG8iKAoWQ0FjY291bnRQcml2YXRlQXBwTGlzdBIOCgZhcHBpZHMYASADKAUiLwotQ0FjY291bnRQcml2YXRlQXBwc19HZXRQcml2YXRlQXBwTGlzdF9SZXF1ZXN0Il8KLkNBY2NvdW50UHJpdmF0ZUFwcHNfR2V0UHJpdmF0ZUFwcExpc3RfUmVzcG9uc2USLQoMcHJpdmF0ZV9hcHBzGAEgASgLMhcuQ0FjY291bnRQcml2YXRlQXBwTGlzdCJPCixDQWNjb3VudFByaXZhdGVBcHBzX1RvZ2dsZUFwcFByaXZhY3lfUmVxdWVzdBIOCgZhcHBpZHMYASADKAUSDwoHcHJpdmF0ZRgCIAEoCCIvCi1DQWNjb3VudFByaXZhdGVBcHBzX1RvZ2dsZUFwcFByaXZhY3lfUmVzcG9uc2UicgpBQ0FjY291bnRQcml2YXRlQXBzQ2xpZW50X05vdGlmeVByaXZhdGVBcHBMaXN0Q2hhbmdlZF9Ob3RpZmljYXRpb24SLQoMcHJpdmF0ZV9hcHBzGAEgASgLMhcuQ0FjY291bnRQcml2YXRlQXBwTGlzdDL9AQoSQWNjb3VudFByaXZhdGVBcHBzEnQKEUdldFByaXZhdGVBcHBMaXN0Ei4uQ0FjY291bnRQcml2YXRlQXBwc19HZXRQcml2YXRlQXBwTGlzdF9SZXF1ZXN0Gi8uQ0FjY291bnRQcml2YXRlQXBwc19HZXRQcml2YXRlQXBwTGlzdF9SZXNwb25zZRJxChBUb2dnbGVBcHBQcml2YWN5Ei0uQ0FjY291bnRQcml2YXRlQXBwc19Ub2dnbGVBcHBQcml2YWN5X1JlcXVlc3QaLi5DQWNjb3VudFByaXZhdGVBcHBzX1RvZ2dsZUFwcFByaXZhY3lfUmVzcG9uc2UyigEKGEFjY291bnRQcml2YXRlQXBwc0NsaWVudBJuChtOb3RpZnlQcml2YXRlQXBwTGlzdENoYW5nZWQSQi5DQWNjb3VudFByaXZhdGVBcHNDbGllbnRfTm90aWZ5UHJpdmF0ZUFwcExpc3RDaGFuZ2VkX05vdGlmaWNhdGlvbhoLLk5vUmVzcG9uc2U", [file_web_ui_common_base]);

/**
 * @generated from message CAccountPrivateAppList
 */
export type CAccountPrivateAppList = Message<"CAccountPrivateAppList"> & {
  /**
   * @generated from field: repeated int32 appids = 1;
   */
  appids: number[];
};

/**
 * @generated from message CAccountPrivateAppList
 */
export type CAccountPrivateAppListJson = {
  /**
   * @generated from field: repeated int32 appids = 1;
   */
  appids?: number[];
};

/**
 * Describes the message CAccountPrivateAppList.
 * Use `create(CAccountPrivateAppListSchema)` to create a new message.
 */
export const CAccountPrivateAppListSchema: GenMessage<CAccountPrivateAppList, CAccountPrivateAppListJson> = /*@__PURE__*/
  messageDesc(file_web_ui_service_accountprivateapps, 0);

/**
 * @generated from message CAccountPrivateApps_GetPrivateAppList_Request
 */
export type CAccountPrivateApps_GetPrivateAppList_Request = Message<"CAccountPrivateApps_GetPrivateAppList_Request"> & {
};

/**
 * @generated from message CAccountPrivateApps_GetPrivateAppList_Request
 */
export type CAccountPrivateApps_GetPrivateAppList_RequestJson = {
};

/**
 * Describes the message CAccountPrivateApps_GetPrivateAppList_Request.
 * Use `create(CAccountPrivateApps_GetPrivateAppList_RequestSchema)` to create a new message.
 */
export const CAccountPrivateApps_GetPrivateAppList_RequestSchema: GenMessage<CAccountPrivateApps_GetPrivateAppList_Request, CAccountPrivateApps_GetPrivateAppList_RequestJson> = /*@__PURE__*/
  messageDesc(file_web_ui_service_accountprivateapps, 1);

/**
 * @generated from message CAccountPrivateApps_GetPrivateAppList_Response
 */
export type CAccountPrivateApps_GetPrivateAppList_Response = Message<"CAccountPrivateApps_GetPrivateAppList_Response"> & {
  /**
   * @generated from field: optional CAccountPrivateAppList private_apps = 1;
   */
  privateApps?: CAccountPrivateAppList;
};

/**
 * @generated from message CAccountPrivateApps_GetPrivateAppList_Response
 */
export type CAccountPrivateApps_GetPrivateAppList_ResponseJson = {
  /**
   * @generated from field: optional CAccountPrivateAppList private_apps = 1;
   */
  privateApps?: CAccountPrivateAppListJson;
};

/**
 * Describes the message CAccountPrivateApps_GetPrivateAppList_Response.
 * Use `create(CAccountPrivateApps_GetPrivateAppList_ResponseSchema)` to create a new message.
 */
export const CAccountPrivateApps_GetPrivateAppList_ResponseSchema: GenMessage<CAccountPrivateApps_GetPrivateAppList_Response, CAccountPrivateApps_GetPrivateAppList_ResponseJson> = /*@__PURE__*/
  messageDesc(file_web_ui_service_accountprivateapps, 2);

/**
 * @generated from message CAccountPrivateApps_ToggleAppPrivacy_Request
 */
export type CAccountPrivateApps_ToggleAppPrivacy_Request = Message<"CAccountPrivateApps_ToggleAppPrivacy_Request"> & {
  /**
   * @generated from field: repeated int32 appids = 1;
   */
  appids: number[];

  /**
   * @generated from field: optional bool private = 2;
   */
  private: boolean;
};

/**
 * @generated from message CAccountPrivateApps_ToggleAppPrivacy_Request
 */
export type CAccountPrivateApps_ToggleAppPrivacy_RequestJson = {
  /**
   * @generated from field: repeated int32 appids = 1;
   */
  appids?: number[];

  /**
   * @generated from field: optional bool private = 2;
   */
  private?: boolean;
};

/**
 * Describes the message CAccountPrivateApps_ToggleAppPrivacy_Request.
 * Use `create(CAccountPrivateApps_ToggleAppPrivacy_RequestSchema)` to create a new message.
 */
export const CAccountPrivateApps_ToggleAppPrivacy_RequestSchema: GenMessage<CAccountPrivateApps_ToggleAppPrivacy_Request, CAccountPrivateApps_ToggleAppPrivacy_RequestJson> = /*@__PURE__*/
  messageDesc(file_web_ui_service_accountprivateapps, 3);

/**
 * @generated from message CAccountPrivateApps_ToggleAppPrivacy_Response
 */
export type CAccountPrivateApps_ToggleAppPrivacy_Response = Message<"CAccountPrivateApps_ToggleAppPrivacy_Response"> & {
};

/**
 * @generated from message CAccountPrivateApps_ToggleAppPrivacy_Response
 */
export type CAccountPrivateApps_ToggleAppPrivacy_ResponseJson = {
};

/**
 * Describes the message CAccountPrivateApps_ToggleAppPrivacy_Response.
 * Use `create(CAccountPrivateApps_ToggleAppPrivacy_ResponseSchema)` to create a new message.
 */
export const CAccountPrivateApps_ToggleAppPrivacy_ResponseSchema: GenMessage<CAccountPrivateApps_ToggleAppPrivacy_Response, CAccountPrivateApps_ToggleAppPrivacy_ResponseJson> = /*@__PURE__*/
  messageDesc(file_web_ui_service_accountprivateapps, 4);

/**
 * @generated from message CAccountPrivateApsClient_NotifyPrivateAppListChanged_Notification
 */
export type CAccountPrivateApsClient_NotifyPrivateAppListChanged_Notification = Message<"CAccountPrivateApsClient_NotifyPrivateAppListChanged_Notification"> & {
  /**
   * @generated from field: optional CAccountPrivateAppList private_apps = 1;
   */
  privateApps?: CAccountPrivateAppList;
};

/**
 * @generated from message CAccountPrivateApsClient_NotifyPrivateAppListChanged_Notification
 */
export type CAccountPrivateApsClient_NotifyPrivateAppListChanged_NotificationJson = {
  /**
   * @generated from field: optional CAccountPrivateAppList private_apps = 1;
   */
  privateApps?: CAccountPrivateAppListJson;
};

/**
 * Describes the message CAccountPrivateApsClient_NotifyPrivateAppListChanged_Notification.
 * Use `create(CAccountPrivateApsClient_NotifyPrivateAppListChanged_NotificationSchema)` to create a new message.
 */
export const CAccountPrivateApsClient_NotifyPrivateAppListChanged_NotificationSchema: GenMessage<CAccountPrivateApsClient_NotifyPrivateAppListChanged_Notification, CAccountPrivateApsClient_NotifyPrivateAppListChanged_NotificationJson> = /*@__PURE__*/
  messageDesc(file_web_ui_service_accountprivateapps, 5);

/**
 * @generated from service AccountPrivateApps
 */
export const AccountPrivateApps: GenService<{
  /**
   * @generated from rpc AccountPrivateApps.GetPrivateAppList
   */
  getPrivateAppList: {
    methodKind: "unary";
    input: typeof CAccountPrivateApps_GetPrivateAppList_RequestSchema;
    output: typeof CAccountPrivateApps_GetPrivateAppList_ResponseSchema;
  },
  /**
   * @generated from rpc AccountPrivateApps.ToggleAppPrivacy
   */
  toggleAppPrivacy: {
    methodKind: "unary";
    input: typeof CAccountPrivateApps_ToggleAppPrivacy_RequestSchema;
    output: typeof CAccountPrivateApps_ToggleAppPrivacy_ResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_web_ui_service_accountprivateapps, 0);

/**
 * @generated from service AccountPrivateAppsClient
 */
export const AccountPrivateAppsClient: GenService<{
  /**
   * @generated from rpc AccountPrivateAppsClient.NotifyPrivateAppListChanged
   */
  notifyPrivateAppListChanged: {
    methodKind: "unary";
    input: typeof CAccountPrivateApsClient_NotifyPrivateAppListChanged_NotificationSchema;
    output: typeof NoResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_web_ui_service_accountprivateapps, 1);

